# Generated by Django 2.2.7 on 2021-11-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=25, verbose_name='Nombre')),
                ('img', models.FileField(upload_to='./img', verbose_name='img')),
                ('fecha_alta', models.DateField(blank=True, null=True, verbose_name='Fecha alta')),
                ('pdf', models.FileField(upload_to='./pdf', verbose_name='pdf')),
            ],
            options={
                'verbose_name_plural': 'Cliente',
            },
        ),
    ]
