# Generated by Django 2.2.7 on 2021-11-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='img',
            field=models.FileField(blank=True, upload_to='./img', verbose_name='img'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='pdf',
            field=models.FileField(blank=True, upload_to='./pdf', verbose_name='pdf'),
        ),
    ]
